
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS notify_email BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_push BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS notify_scan_alerts BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_weekly_summary BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS saved_brands TEXT[] NOT NULL DEFAULT '{}'::text[];
