// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL =
      process.env.VITE_SUPABASE_URL ||
      process.env.SUPABASE_URL ||
      'https://uqyxssgiqdimyhubkmfd.supabase.co';

    const SUPABASE_PUBLISHABLE_KEY =
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_ANON_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_ANON_KEY ||
      'sb_publishable_W7m8pl202ruGN1a6CIbEqg_Qnluj18u';

    const request = getRequest();
    const authHeader = request?.headers?.get('authorization');

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      console.warn('[Supabase Auth] Missing Authorization header, returning guest context.');
      return next({
        context: {
          supabase: createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY),
          user: null,
          userId: null,
          claims: null,
          isAuthenticated: false,
        },
      });
    }

    const token = authHeader.replace('Bearer ', '').trim();
    if (!token || token.split('.').length !== 3) {
      console.warn('[Supabase Auth] Invalid token format, returning guest context.');
      return next({
        context: {
          supabase: createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY),
          user: null,
          userId: null,
          claims: null,
          isAuthenticated: false,
        },
      });
    }

    try {
      const supabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims?.sub) {
        console.warn('[Supabase Auth] Claim verification failed, returning guest context:', error?.message);
        return next({
          context: {
            supabase,
            user: null,
            userId: null,
            claims: null,
            isAuthenticated: false,
          },
        });
      }

      return next({
        context: {
          supabase,
          user: { id: data.claims.sub },
          userId: data.claims.sub,
          claims: data.claims,
          isAuthenticated: true,
        },
      });
    } catch (err) {
      console.warn('[Supabase Auth] Auth verification exception, returning guest context:', err);
      return next({
        context: {
          supabase: createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY),
          user: null,
          userId: null,
          claims: null,
          isAuthenticated: false,
        },
      });
    }
  },
);

export const optionalSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL =
      process.env.VITE_SUPABASE_URL ||
      process.env.SUPABASE_URL ||
      'https://uqyxssgiqdimyhubkmfd.supabase.co';

    const SUPABASE_PUBLISHABLE_KEY =
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_ANON_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_ANON_KEY ||
      'sb_publishable_W7m8pl202ruGN1a6CIbEqg_Qnluj18u';

    const request = getRequest();
    const authHeader = request?.headers?.get('authorization');

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      console.warn('[Supabase Auth] No authorization header provided for optional auth.');
      return next({
        context: {
          user: null,
          userId: null,
          isAuthenticated: false,
          supabase: createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY),
        },
      });
    }

    const token = authHeader.replace('Bearer ', '').trim();
    if (!token || token.split('.').length !== 3) {
      console.warn('[Supabase Auth] Invalid token structure for optional auth.');
      return next({
        context: {
          user: null,
          userId: null,
          isAuthenticated: false,
          supabase: createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY),
        },
      });
    }

    try {
      const supabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims?.sub) {
        console.warn('[Supabase Auth] Token claim verification failed for optional auth:', error?.message);
        return next({
          context: {
            user: null,
            userId: null,
            isAuthenticated: false,
            supabase,
          },
        });
      }

      return next({
        context: {
          supabase,
          user: { id: data.claims.sub },
          userId: data.claims.sub,
          claims: data.claims,
          isAuthenticated: true,
        },
      });
    } catch (err) {
      console.warn('[Supabase Auth] Exception in optional auth handler:', err);
      return next({
        context: {
          user: null,
          userId: null,
          isAuthenticated: false,
          supabase: createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY),
        },
      });
    }
  },
);
